version: 2
workflows:
  version: 2
  build:
    jobs:
      - build_and_test
      - publish_github_release:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
                - development
      - deploy_to_production:
          requires:
            - publish_github_release
          filters:
            branches:
              only: master

jobs:
  build_and_test:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: npm install
      - run: 
          name: "Build"
          command: npm run-script build
      - run: 
          name: "Test"
          command: npm test
      - run:
          name: "Zip file"
          command: zip -r app ./build
      - persist_to_workspace:
          root: ./ 
          paths: .

  deploy_to_production:
    docker:
      - image: circleci/node:10.15.1
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Deploy to Staging"
          command: npx surge build/ https://thands-first-app.surge.sh
